export const GET_PEOPLE_REQUEST = "GET_PEOPLE_REQUEST"
export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS"
export const GET_PEOPLE_FAIL = "GET_PEOPLE_FAIL"

export const GET_PLANET_REQUEST = "GET_PLANET_REQUEST"
export const GET_PLANET_SUCCESS = "GET_PLANET_SUCCESS"
export const GET_PLANET_FAIL = "GET_PLANET_FAIL"

export const GET_SHIPS_REQUEST = "GET_SHIPS_REQUEST"
export const GET_SHIPS_SUCCESS = "GET_SHIPS_SUCCESS"
export const GET_SHIPS_FAIL = "GET_SHIPS_FAIL"

export const GET_SINGLE_REQUEST = "GET_SINGLE_REQUEST"
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS"
export const GET_SINGLE_FAIL = "GET_SINGLE_FAIL"